### ISSUE TITLE
Cannot Edit Textures

### ISSUE THREAD

**Issue by Tyler-Hecht** [DeflatedPickle/Quiver#11]
I can open the textures but I cannot edit them. The edit button is gray.

**Comment by DeflatedPickle** [comment]
@RadiateGold, yes! Because I never made an editor. See, it's called an "image *viewer*". But good news! You can use my stand-alone image editor, [Rawky](https://github.com/DeflatedPickle/Rawky) (I'm re-writing this program soon, it'll include a trimmed-down, more Minecraft-focused version of Rawky).
