### ISSUE TITLE
array element type mismatch

### ISSUE THREAD

**Issue by tinyurl-com-u7do327** [DeflatedPickle/Quiver#45]
**Describe the bug**
It gives you a warn and a Java error.
**To Reproduce**
1. Go to 'C:\Users\yourname\Downloads\Quiver-1.7.0\Quiver-1.7.0'
2. Click on 'quiver.bat'
3. Get [WARN ] timestamp (x ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: main threw java.lang.IllegalArgumentException: array element type mismatch         com.deflatedpickle.quiver.launcher.MainKt$main$2.uncaughtException(main.kt:83)

**Expected behavior**
I expected it to launch properly. This is my first time using Quiver.

**Screenshots**
![error](https://user-images.githubusercontent.com/71940013/111389622-84f36400-866e-11eb-9c45-2d5768baa68a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by DeflatedPickle** [comment]
Hello! Thank you for reporting this error, however it should have been reported to [Haruhi](https://github.com/DeflatedPickle/haruhi) as that's the indicated fail point given by the logged information. However, I'm faily sure I've seen others have this before and it was due to using Java 9+ (it's indicated in the README that this only works for Java 8), but you've cut off the part in the console that logs what Java version is being used. If you could scroll that up and confirm the Java version you're using, or copy and paste the entier log, that could sort this out quite quickly

Thanks again, I always appreciate having issues brought up rather than people dismissing the software

**Comment by tinyurl-com-u7do327** [comment]
[DEBUG] 15:44:05 (603 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Installed JANSI for this terminal session
        com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:45)
[INFO ] 15:44:05 (664 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt:
OS  : WINDOWS (windows 10)
Java: null (null)
Dir : C:\Users\royyi\Downloads\Quiver-1.7.0\Quiver-1.7.0
Dev?: false
        com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:52)
[DEBUG] 15:44:05 (1145 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Registered a default exception handler
        com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:99)
[INFO ] 15:44:05 (1173 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Created the plugins folder at C:\Users\royyi\Downloads\Quiver-1.7.0\Quiver-1.7.0\plugins
        com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:106)
[INFO ] 15:44:05 (1179 ms since JVM launch) [main/1] ClassGraphUtil: Found the plugin JARs: [core-1.2.0.jar, filepanel-1.0.0.jar, filetable-1.0.1.jar, foldertree-1.0.0.jar, imageviewer-1.0.0.jar, launcher-1.0.0.jar, master.jar, packexport-1.0.0.jar, packsquashstep-1.0.0.jar, tableviewer-1.0.0.jar, textviewer-1.0.0.jar, treeviewer-1.0.0.jar, zipstep-1.0.0.jar]
        com.deflatedpickle.haruhi.util.ClassGraphUtil.<clinit>(ClassGraphUtil.kt:29)
[DEBUG] 15:44:05 (1266 ms since JVM launch) [main/1] com.deflatedpickle.haruhi.util.PluginUtil: Found the plugin ImageViewerPlugin from com.deflatedpickle.imageviewer
        com.deflatedpickle.haruhi.util.PluginUtil.discoverPlugins(PluginUtil.kt:93)
[DEBUG] 15:44:05 (1271 ms since JVM launch) [main/1] com.deflatedpickle.haruhi.util.PluginUtil: Found the plugin Quiver from com.deflatedpickle.quiver
        com.deflatedpickle.haruhi.util.PluginUtil.discoverPlugins(PluginUtil.kt:93)
[DEBUG] 15:44:05 (1272 ms since JVM launch) [main/1] com.deflatedpickle.haruhi.util.PluginUtil: Found the plugin FilePanelPlugin from com.deflatedpickle.quiver.filepanel
        com.deflatedpickle.haruhi.util.PluginUtil.discoverPlugins(PluginUtil.kt:93)
[DEBUG] 15:44:06 (1276 ms since JVM launch) [main/1] com.deflatedpickle.haruhi.util.PluginUtil: Found the plugin FileTablePlugin from com.deflatedpickle.quiver.filetable
        com.deflatedpickle.haruhi.util.PluginUtil.discoverPlugins(PluginUtil.kt:93)
[WARN ] 15:44:06 (1279 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: main threw java.lang.IllegalArgumentException: array element type mismatch
        com.deflatedpickle.quiver.launcher.MainKt$main$2.uncaughtException(main.kt:83)

**Comment by DeflatedPickle** [comment]
> Java: null (null)

Well, that might have to be logged differently on each platform. Could you check what version it's running with outside of the program, please?

**Comment by tinyurl-com-u7do327** [comment]
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

**Comment by DeflatedPickle** [comment]
Well, that's pretty telling. Could you try running it with Java 8, please? In the future I will offer release artifacts with a Java 8 JVM bundled but I've been working on other things

**Comment by tinyurl-com-u7do327** [comment]
Ok.

**Comment by tinyurl-com-u7do327** [comment]
Working properly now, thanks!

**Comment by DeflatedPickle** [comment]
Glad to hear it! Thank you for trying out the program and please report any weird things you find with it and tell me any suggestions you have

**Comment by AlexTMjugador** [comment]
Out of curiosity, has someone investigated this Java 9+ incompatibility thoroughly? If so, are there any ideas that may be relevant to fix it? I've skimmed through Haruhi and didn't find anything that obviously screams incompatibility with newer Java versions, but [Java 8 support is complicated](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) if you are an Oracle customer, it won't last that long if you're not, and it'd be nice to be able to use something more modern.

**Comment by DeflatedPickle** [comment]
Nope, as far as I know this project only has me working on it and I'm too busy writing new features to justify it's existance, but it might be as simple as; it needs to be compiled with Java 9 to be ran with it. Also, anecdotally, when I originally shared [Rawky](https://github.com/DeflatedPickle/Rawky/tree/backup) around, which is a project that birthed [Haruhi](https://github.com/DeflatedPickle/haruhi) and a few other utilities that Quiver makes use of, people ran into issues because I was targeting Java 9, as anyone who tested it was running Java 8, since that's what Minecraft uses (though I think it now bundles a JRE), which people probably have if they're using Quiver.
