### ISSUE TITLE
.bat unresponsive

### ISSUE THREAD

**Issue by mathancy** [DeflatedPickle/Quiver#75]
After downloading the most recent version of Quiver (1.9.1), and unzipping to desktop, the quiver.bat file doesn't do anything. No cmd prompt, no window, no tasks in Task Manager. Even running as Admin doesn't solve the issue. Perhaps a conflict with the most recent Windows update? (Update 20H2, OS Build 19042.928)

I'm running Windows 10 Home. Ryzen 5 3600 + R9 290. Memory is not an issue, nor is storage.

**Comment by DeflatedPickle** [comment]
Could you please let me know what version of Java you're using?

**Comment by mathancy** [comment]
I'm using Java JRE 1.8.0_291

**Comment by mathancy** [comment]
Small update, the command prompt does in fact open, but only for a split second. Without dissecting the script, I'm at a loss for why it crashes immediately

**Comment by DeflatedPickle** [comment]
Oh, alright. Thanks for that. Could you try opening a command prompt in the same folder as the `.bat` and run `./Quiver.bat`? That should keep the console open so you can read the text in it

**Comment by mathancy** [comment]
I figured this was the issue, I've checked my Java config and have found no way of setting "Home"

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by DeflatedPickle** [comment]
Ah, that'll be it then. Maybe ~~[this answer](https://superuser.com/a/284351)~~ [this guide](https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html) can help you set it?

**Comment by mathancy** [comment]
I set the variables up correctly (using "echo %JAVA_HOME% in a command prompt fires back the correct location), however the command prompt for Quiver still closes immediately.

Oddly, now when trying to load the .bat through a command prompt directly, I get this error (that I definitely was not getting before).
![image](https://user-images.githubusercontent.com/81835335/115719127-b4834380-a373-11eb-86c7-0c627cd718df.png)

Previously I was just getting the "JAVA_HOME is not set" error

**Comment by DeflatedPickle** [comment]
After looking around, this might be caused by gradle/gradle#1989? Here's a `.bat` with [this](https://github.com/gradle/gradle/issues/1989#issuecomment-395001392) proposed solution. Could you replace the current one with it and let me know if it fixes this?

[Quiver.zip](https://github.com/DeflatedPickle/Quiver/files/6358690/Quiver.zip)

**Comment by mathancy** [comment]
Ah, worked like a charm! Brilliant! Thank you so much!

**Comment by DeflatedPickle** [comment]
Great! I'll publish a hotfix immediately. Thank you for bringing this to my attention!

**Comment by mathancy** [comment]
Might I suggest a script to automatically set the Java path? Could be worth looking into, as that type of super user management would mean a lot less accessibility. Thanks so much for your help!

**Comment by DeflatedPickle** [comment]
> Might I suggest a script to automatically set the Java path

I think most installers for JRE's include a bit to add it to the path and set environment variables? Though I will add a note about it. I am hoping to offer releases with a similar directory setup but using executable binaries instead of the scripts, but I haven't looked into it yet

> Thanks so much for your help!

Of course! Quiver is written for the user! I'm always happy to help when I can!

Lastly, if you run into any other quirks or find missing parts, or have suggestions, please make them known in new issues so I can get to them. I currently mainly only have my perspective and I'd really like feedback from users
